# ==========================================
# TEMA: GRUVBOX DARK (PRO EDITION)
# ==========================================

# Definizione della palette Gruvbox
$bg = rgb(282828)
$surface = rgb(1d2021)
$primary = rgb(d79921)
$tertiary = rgb(d65d0e)
$inactive = rgb(3c3836)
$text = rgb(ebdbb2)


