# ==========================================
# TEMPLATE: HYPRLOCK COLORS
# ==========================================

$text_color = rgb(ebdbb2)
$surface_alpha = rgba(3c3836d9)
$tertiary = rgb(d79921)
$surface = rgb(3c3836)

$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$font_symbols = JetBrainsMono Nerd Font
