# ==========================================
# TEMPLATE: HYPRLAND COLORS
# ==========================================

$bg = rgb(282828)
$surface = rgb(3c3836)
$primary = rgb(d79921)
$tertiary = rgb(fe8019)
$inactive = rgb(504945)
$text = rgb(ebdbb2)
