# ==========================================
# GRUVBOX DARK - HYPRLOCK COLORS
# ==========================================

$text_color = rgb(ebdbb2)
$surface_alpha = rgba(40, 40, 40, 0.85)
$tertiary = rgb(d79921)
$surface = rgb(1d2021)

$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$font_symbols = JetBrainsMono Nerd Font
