# Output generato in: ~/.dotfiles/themes/palette/matugen/hyprlock.conf

$primary            = rgb(e9c16c)
$on_primary         = rgb(3f2e00)
$surface            = rgba(17130bcc)
$surface_container  = rgba(2e2921e6)
$on_surface         = rgb(ebe1d4)
$on_surface_variant = rgb(d0c5b4)
$outline            = rgba(998f8080)
$error              = rgb(ffb4ab)
$shadow             = rgba(00000066)
