# ==========================================
# TEMPLATE: HYPRLOCK COLORS
# ==========================================

$text_color = rgb({{fg_clean}})
$surface_alpha = rgba({{bg0_clean}}d9)
$tertiary = rgb({{primary_clean}})
$surface = rgb({{bg0_clean}})

$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$font_symbols = JetBrainsMono Nerd Font
