# ==========================================
# TEMPLATE: HYPRLAND COLORS
# ==========================================

$bg = rgb({{bg_clean}})
$surface = rgb({{bg0_clean}})
$primary = rgb({{primary_clean}})
$tertiary = rgb({{tertiary_clean}})
$inactive = rgb({{inactive_clean}})
$text = rgb({{fg_clean}})
