# ==========================================
# TYPOGRAPHY & WINDOW
# ==========================================
font_size        12.0
background_opacity 0.85
dynamic_background_opacity yes
allow_remote_control yes

# Dynamic Kitty Theme
background  {{bg}}
foreground  {{fg}}
cursor      {{fg}}
selection_background {{tertiary}}
selection_foreground {{bg}}

# Colori normali
color0      {{bg}}
color1      {{red}}
color2      {{accent}}
color3      {{primary}}
color4      {{blue}}
color5      {{purple}}
color6      {{cyan}}
color7      {{fg_dim}}

# Colori chiari
color8      {{inactive}}
color9      {{red}}
color10     {{accent}}
color11     {{secondary}}
color12     {{blue}}
color13     {{purple}}
color14     {{cyan}}
color15     {{fg}}
