# ==========================================
# HYPRLAND - CONFIGURAZIONE COMUNE
# ==========================================
source = ~/.dotfiles/themes/palette/current/hyprland.conf.tmpl-colors.conf
source = ~/.dotfiles/hypr/modules/programs.conf
source = ~/.dotfiles/hypr/modules/autostart.conf
source = ~/.dotfiles/hypr/modules/variables.conf
source = ~/.dotfiles/hypr/modules/decorations.conf
source = ~/.dotfiles/hypr/modules/animations.conf
source = ~/.dotfiles/hypr/modules/inputs.conf
source = ~/.dotfiles/hypr/modules/settings.conf
source = ~/.dotfiles/hypr/modules/keybinds.conf
source = ~/.dotfiles/hypr/modules/windowsrule.conf
source = ~/.dotfiles/hypr/modules/workspacerules.conf
