# ==========================================
# TEMPLATE: HYPRLOCK COLORS
# ==========================================

$text_color = rgb(c0caf5)
$surface_alpha = rgba(24283bd9)
$tertiary = rgb(7aa2f7)
$surface = rgb(24283b)

$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$font_symbols = JetBrainsMono Nerd Font
