# ==========================================
# TEMPLATE: HYPRLAND COLORS
# ==========================================

$bg = rgb(1a1b26)
$surface = rgb(24283b)
$primary = rgb(7aa2f7)
$tertiary = rgb(ff9e64)
$inactive = rgb(414868)
$text = rgb(c0caf5)
