# ==========================================
# TEMPLATE: HYPRLOCK COLORS
# ==========================================

$text_color = rgb(d3c6aa)
$surface_alpha = rgba(343f44d9)
$tertiary = rgb(dbbc7f)
$surface = rgb(343f44)

$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$font_symbols = JetBrainsMono Nerd Font
