# ==========================================
# TEMPLATE: HYPRLAND COLORS
# ==========================================

$bg = rgb(2d353b)
$surface = rgb(343f44)
$primary = rgb(dbbc7f)
$tertiary = rgb(e69875)
$inactive = rgb(4f5b58)
$text = rgb(d3c6aa)
