# ==========================================
# TYPOGRAPHY & WINDOW
# ==========================================
font_size        12.0
background_opacity 0.85
dynamic_background_opacity yes
allow_remote_control yes

# Dynamic Kitty Theme
background  #2d353b
foreground  #d3c6aa
cursor      #d3c6aa
selection_background #e69875
selection_foreground #2d353b

# Colori normali
color0      #2d353b
color1      #e67e80
color2      #a7c080
color3      #dbbc7f
color4      #7fbbb3
color5      #d699b6
color6      #83c092
color7      #9da9a0

# Colori chiari
color8      #4f5b58
color9      #e67e80
color10     #a7c080
color11     #d9bb80
color12     #7fbbb3
color13     #d699b6
color14     #83c092
color15     #d3c6aa
