# Avvia lo script che ruota le immagini ogni 3/5 minuti
exec-once = awww-daemon
exec-once = ~/.dotfiles/hypr/scripts/wallpaper.sh &
# Avvia e sblocca il portachiavi di sistema
exec-once = gnome-keyring-daemon --start --components=secrets
