# Avvia lo script che ruota le immagini ogni 3/5 minuti
exec-once = caelestia shell -d
#exec-once = hyprlock

exec-once = awww-daemon
exec-once = ~/.dotfiles/hypr/scripts/wallpaper.sh &

exec-once = mako

# Avvia e sblocca il portachiavi di sistema
exec-once = gnome-keyring-daemon --start --components=secrets
