#  ┏┓┳┓┏┓┏┓┳┓┏┓┳┳┓┏┓
#  ┃┃┣┫┃┃┃┓┣┫┣┫┃┃┃┗┓
#  ┣┛┛┗┗┛┗┛┛┗┛┗┛ ┗┗┛
#                   

$terminal = kitty
#$fileManager = thunar
$volumecontrol = pavucontrol
$browser = google-chrome
#$music = $HOME/.spicetify/spicetify watch -q -s &
