# Regola per Kitty (Opacità attiva 90% e inattiva 80%)
windowrule = match:class ^(kitty)$, opacity 0.9 0.8

# Regola per il WiFi (Esempio con nm-connection-editor)
windowrule = match:class ^(wofi)$, opacity 0.95 0.85

layerrule = blur on, match:namespace wofi
layerrule = animation slide, match:namespace wofi

blurls = mako
